server:
  port: 8081
spring:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
